### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by pvpscript** [pvpscript/mdtoc#1]
- [ ] Make it work for inserting and updating a table of contents
	- [x] Calculate the starting point and ending point of the TOC
	- [ ] Calculate the new size between the delimiters, based on the length of the TOC and the difference between the ending point and the starting point
	- [ ] Move the content ahead, if necessary
	- [ ] Write to the file
- [ ] Write the README.md using the table of contents generator
	- [ ] Write about what it does
	- [ ] How to install it
	- [ ] How to use it
	- [ ] Advantages between this build and other ones that already exists
	- [ ] Explain the usage of HTML tags and show the tests in that site

- [ ] Change macros to static const variables

**Comment by pvpscript** [comment]
- [ ] Modify parse_toc to return the start offset and end offset of the given section
